{
 "title": "WP04 Portal Server",
 "description": "Simple sample Dashboard to show PMI data",
 "tags": [
  "pmi",
  "tWAS"
 ],
 "time": { "from": "now-2h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "JVM Data",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT ProcessCpuUsage.count as CpuUsage, UpTime.count as UpTime, HeapSize.value as HeapSize, UsedMemory.count as UsedMemory FROM cell WHERE (\"node\" = 'wp04Node' AND \"j2eetype\" = 'JVM_Runtime') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "JDBC jdbc/wpdbDS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select PoolSize.value as PoolSize, FreePoolSize.value as FreePoolSize, (PoolSize.value - FreePoolSize.value) as UsedConnections from \"cell\" WHERE (\"node\" = 'wp04Node' AND \"label5\" = 'jdbc/wpdbDS') and $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "WebContainer Thread pool",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "cell",
     "query": "SELECT \"PoolSize.value\", \"ActiveCount.value\" FROM \"cell\" WHERE (\"node\" = 'wp04Node' AND \"module\" = 'WebContainer') AND $timeFilter",
     "select": [
      [
       { "params": [ "PoolSize.value" ], "type": "field" }
      ],
      [
       { "params": [ "ActiveCount.value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=", "value": "wp04Node" },
      { "condition": "AND", "key": "module", "operator": "=", "value": "WebContainer" }
     ]
    }
   ]
  }
 ]
}